FROM ghcr.io/hardomx/neovim:latest
LABEL org.opencontainers.image.source=https://github.com/hardomx/nvim-containers

USER root

RUN apt update \
    && apt install python3-full python-is-python3 python3-pylsp python3-debugpy -y

USER dev

RUN nvim --headless +qa

CMD ["sleep", "infinity"]
